### ISSUE TITLE
Chrome Extension seems to not be mapping consistently

### ISSUE THREAD

**Issue by geckoseo** [livestyle/issues#49] opened 2015-09-23 14:18 UTC
Picking up where we left off on:

https://github.com/livestyle/sublime-text/issues/5

> I have been noticing this a lot recently with the Alpha version.
> 
> If I open a remote stylesheet via sftp and edit the file directly on
> the server, at first LiveStyle seems to map it correctly to Sublime.
> 
> If I refresh the browser page though, the bi-directional mapping seems
> to break, and all the available stylesheets on the dropdown are no
> longer visible.
> 
> I then need to add the remote stylesheet as user stylesheet 1.
> 
> This still allows live update from Sublime to happen on the website,
> but the bi-direction mapping is broken, so any edits made in Chrome
> Dev tools does not update the stylesheet in Sublime.
> 
> If I close Dev Tools, then re-open it, all the stylesheets reappear in
> the LiveStyle dropdown in Chrome, and the bi-directional editing works
> again until I refresh the browser window, at which time it breaks
> again until I close Dev Tools.
> 
> It's possible this might be cache related, although I am struggling to
> find the root cause.

To answer the last question, yes, I uninstalled the old version completely from Chrome as well as from Sublime..

I will go see if I can reproduce it on a different machine..

**Comment by sergeche** [comment] 2015-09-23 14:20
Does this issue reproduces for SFTP files? Do you have another tab opened with the same page?
You can also go to Preferences > Extensions, enable Developer mode and click on `background.html` link for LiveStyle extension, it will open DevTools for background page with extensive logging in console, there might be some hints

**Comment by geckoseo** [comment] 2015-09-23 14:25
I'll give it a try and report back.

I have multiple tabs open, but it also happens if I use an isolated chrome profile.

I will also test it using a bi-directional sync with the remote server using a push/pull tool rather than working on the actual live remote file to see if there is any relation.

**Comment by sergeche** [comment] 2015-09-23 14:27
LS doesn’t update actual files, it only updates files opened in editor and you have to save them manually. So there might be something with local connection or CSS parsing errors (you can see them in bg page devtools)

**Comment by geckoseo** [comment] 2015-09-23 14:31
Sure, I'm thinking it might be related to the FTP connection between the server and my local machine, so I will do a test by using a local file to sync to the remote server, rather than using the remote file as a tmp instance.

i.e, edit the local file (synced with LS), then push it upstream to the server so I am only working locally as far as LS is concerned..

But I will try the bg checks first..

**Comment by geckoseo** [comment] 2015-09-23 15:05
It is definitely related to Chrome Dev tools being open, and I can reproduce it another machine.

The messages I get back when refreshing the page with Dev Tools open are:

[DevTools] Received message Object {name: "reset"}
background.js:1183 [DevTools] Loaded stylesheets: []
background.js:1642 Destroy model for http://my-domain.com/
background.js:1183 [DevTools] Received message Object {name: "get-stylesheets"}
background.js:1183 [DevTools] Received message Object {name: "get-stylesheets"}
background.js:967 send socket message rv-ping

The get-stylesheets on refresh doesn't seem to do anything.

If I copy the remote stylesheet to a local file, the problem remains, so it doesn't seem to be related to working directly on the remote file via sftp.

Is there some kind of Diff checking going on in the background?

I don't currently have a diff checker in my path.. 

Using Windows 10, Chrome latest, Sublime 3 Build 3083

**Comment by sergeche** [comment] 2015-09-23 15:08
LS uses tries to retrieve a list of available page stylesheets from DevTools if they are opened, because it’s more accurate and required for browser→editor updates. I some cases it may return empty list. Need to figure out why

**Comment by geckoseo** [comment] 2015-09-23 15:12
Anything I can do to help?

**Comment by sergeche** [comment] 2015-09-23 15:18
I’m pretty busy with LS web-site right now. I’ll get back to this issue when I’m done.
Do you have query params in stylesheet URLs?

**Comment by geckoseo** [comment] 2015-09-23 15:35
yes, it is a Wordpress site, so all the plugin and theme stylesheets have query params..

I just wrote a function to strip query strings from the static files, and it seems to have stabilised it..

Will keep testing

**Comment by sergeche** [comment] 2015-09-23 15:38
Looks the same as https://github.com/emmetio/livestyle-sublime/issues/150

**Comment by geckoseo** [comment] 2015-09-23 15:42
Yes, looks same. I will post the php function which appears to patch the problem in Wordpress for now on that ticket..

**Comment by sergeche** [comment] 2015-10-20 22:12
Fixed in v0.9.4 Chrome extension

**Closed as completed by sergeche** 2015-10-20 22:12 UTC
