### ISSUE TITLE
LiveStyle Alpha 0.9 – Lots of missing variable errors

### ISSUE THREAD

**Issue by eablokker** [livestyle/issues#47] opened 2015-08-15 00:10 UTC
I'm getting lots of Missing variable errors.
I'm getting other errors that seem to have an issue with negative margin values.
I have the livestyle extension pointing to my main .scss file which @imports all the other files, so I don't know how any variables can be missing. But obviously there is a problem because it thinks some CSS attribute values are variables.

I am using Compass in my project, maybe that could be screwing things up?

``` console
send socket message request-files
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "$color-white"
worker.js:480 Missing variable "$color-grey"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "pointer"
2worker.js:480 Missing variable "auto"
background.js:968 send socket message request-files
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "solid"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
2worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "$color-font-headline"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "cover"
worker.js:480 Missing variable "$color-blue"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "bold"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "inherit"
worker.js:480 Missing variable "$color-font-light"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "$color-background"
worker.js:480 r {name: "r", message: "Unable to evaluate expression "0 -10px": Unexpected number at column 3 in expression 0 -10px", fileName: "--retracted--/scss/modules/_news-grid.scss", lineNumber: 118, columnNumber: 15…}o.extend.error @ worker.js:480o @ worker.js:481u @ worker.js:481eval @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481(anonymous function) @ worker.js:481s @ worker.js:480(anonymous function) @ worker.js:480module.exports.respond @ worker.js:423module.exports.files @ worker.js:210module.exports @ worker.js:200handleMessage @ worker.js:461
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "$color-background-2"
worker.js:480 Missing variable "relative"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "rgba"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "$color-white"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "none"
worker.js:480 Missing variable "auto"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "left"
2worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
background.js:968 send socket message request-files
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "solid"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
2worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "$color-font-headline"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "cover"
worker.js:480 Missing variable "$color-blue"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "bold"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "inherit"
worker.js:480 Missing variable "$color-font-light"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "$color-background"
worker.js:480 r {name: "r", message: "Unable to evaluate expression "0 -10px": Unexpected number at column 3 in expression 0 -10px", fileName: "--retracted--/scss/modules/_news-grid.scss", lineNumber: 118, columnNumber: 15…}o.extend.error @ worker.js:480o @ worker.js:481u @ worker.js:481eval @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481(anonymous function) @ worker.js:481s @ worker.js:480(anonymous function) @ worker.js:480module.exports.respond @ worker.js:423module.exports.files @ worker.js:210module.exports @ worker.js:200handleMessage @ worker.js:461
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "$color-background-2"
worker.js:480 Missing variable "relative"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "rgba"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "$color-white"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "none"
worker.js:480 Missing variable "auto"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "left"
2worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
background.js:968 send socket message diff
background.js:968 send socket message request-files
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "solid"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
2worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "$color-font-headline"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "cover"
worker.js:480 Missing variable "$color-blue"
worker.js:480 Missing variable "inline-block"
worker.js:480 Missing variable "bold"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "inherit"
worker.js:480 Missing variable "$color-font-light"
worker.js:480 Missing variable "$color-border"
worker.js:480 Missing variable "center"
worker.js:480 Missing variable "$color-background"
worker.js:480 r {name: "r", message: "Unable to evaluate expression "0 -10px": Unexpected number at column 3 in expression 0 -10px", fileName: "--retracted--/scss/modules/_news-grid.scss", lineNumber: 118, columnNumber: 15…}o.extend.error @ worker.js:480o @ worker.js:481u @ worker.js:481eval @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481resolve @ worker.js:481v.scope.u.transform @ worker.js:481(anonymous function) @ worker.js:481v.scope.u.next @ worker.js:481(anonymous function) @ worker.js:481s @ worker.js:480(anonymous function) @ worker.js:480module.exports.respond @ worker.js:423module.exports.files @ worker.js:210module.exports @ worker.js:200handleMessage @ worker.js:461
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "relative"
worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "$color-background-2"
worker.js:480 Missing variable "relative"
2worker.js:480 Missing variable "none"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "rgba"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "absolute"
worker.js:480 Missing variable "$color-white"
worker.js:480 Missing variable "transparent"
worker.js:480 Missing variable "none"
worker.js:480 Missing variable "auto"
worker.js:480 Missing variable "block"
worker.js:480 Missing variable "left"
2worker.js:480 Missing variable "auto"
2worker.js:480 Missing variable "none"
```

**Comment by sergeche** [comment] 2015-10-17 20:45
The next LiveStyle update will remove most of these irrelevant messages.
About “real” missing variables. In order to pick variables defined outside of current file, they must be directly `@import`’ed into file you’re editing or added as global dependencies: http://livestyle.io/docs/preprocessors/

And I see there’s expression evaluation error, can you a complete expression (SCSS property with value) where that emitted error message? The message should give enough hints about this expression in your code.

**Comment by sergeche** [comment] 2015-10-20 22:44
Confirm that `0 -10px` expression by itself causes parsing errors

**Comment by sergeche** [comment] 2015-10-20 22:46
Duplicate of #54

**Closed as completed by sergeche** 2015-10-20 22:46 UTC
Labels: bug, need more info
