### ISSUE TITLE
Can not use LiveStyle for develop chrome extension after update to 1.0.1

### ISSUE THREAD

**Issue by tientamle** [livestyle/issues#81] opened 2015-12-29 17:11 UTC
thanks

**Comment by melody7426** [comment] 2015-12-29 17:14
```Error in event handler for (unknown): TypeError: Cannot read property 'livestyle:1' of undefined
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/background.js:633:39handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:376EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnDisconnect @ extensions::messaging:296```

**Comment by franciscolourenco** [comment] 2015-12-29 21:36
Also having this problem, but at the same time also doesn't work with `file://`

**Comment by sergeche** [comment] 2015-12-29 21:38
Just pushed v1.0.2.
You mean that you have the same error when adding custom stylesheet for in `file://` page? Or LiveStyle doesn’t work at all?

**Comment by franciscolourenco** [comment] 2015-12-29 21:40
It doesn't detect any stylesheets and the `add stylesheet button` doesn't do anything.

![screen shot 2015-12-29 at 22 40 03](https://cloud.githubusercontent.com/assets/208149/12042638/338aee2c-ae7d-11e5-9c92-96ad2d0021ba.png)

**Comment by sergeche** [comment] 2015-12-29 21:42
Try to reload the page, does issue still exists? Does this page contains external stylesheets?

**Comment by franciscolourenco** [comment] 2015-12-29 22:29
Yes still exists, separate stylesheets but local.

```
    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="fonts/fontello/css/fontello.css">
    <link rel="stylesheet" href="css/fonts.css">
    <link rel="stylesheet" href="css/options.css">
    <link rel="stylesheet" href="css/animate.css">
```

**Comment by sergeche** [comment] 2015-12-29 22:35
What’s LiveStyle Chrome plugin is installed? Do you see any errors in DevTools console and `background.html` page (see http://livestyle.io/docs/troubleshooting/)?

**Comment by franciscolourenco** [comment] 2015-12-29 22:42
Hadn't enable access to files and folders. Read every page except troubleshoot. Sorry for this. Maybe it could be put in the `Getting Started` page?

So its just the problem with `chrome-extension://`

**Comment by sergeche** [comment] 2015-12-29 23:00
Should work in v1.0.3

**Comment by melody7426** [comment] 2015-12-30 04:30
That’s really nice. Thank you so much Sergeche.

**Comment by melody7426** [comment] 2015-12-30 05:23
Maybe something else happened.
When I updated something at the sublime text. I see the updated was sent and the background page can receive it. but it returns undefined. And the style does not update on the page (I mean chrome extension page).

`set model origin undefined background.js:1479`

**Comment by DeoThemes** [comment] 2015-12-30 06:30
Hello.

I think I'm having a similar issue. After version 1.0.0 released LiveStyle doesn't work anymore. I just have a message in Chrome Extension - "No connected editor" But I use ST3 with newest version of LiveStyle. I've tried to install LiveStyle app and here is the message - http://clip2net.com/s/3soNIvf

Previous versions worked (with opened dev tool panel).
I already checked firewall and antivirus, everything is fine.

Can you help with this issue?

Thanks.

**Comment by sergeche** [comment] 2015-12-30 08:11
> `set model origin undefined background.js:1479`

it’s not an error or the cause of issue. How does your chrome extension URL look like?

>  I just have a message in Chrome Extension - "No connected editor" But I use ST3 with newest version of LiveStyle. 

Most likely your ST plugin wasn’t updated properly. Can you open ST console and see if there are any errors?

As for permanent `Checking status` message, can you click on app window, press F12 and check if there are errors in console of opened DevTools?

**Comment by DeoThemes** [comment] 2015-12-30 08:23
I have this message in console - WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms

**Comment by sergeche** [comment] 2015-12-30 08:24
Yes, it’s an old plugin. Did you installed it via Package Control? Try to remove it and install again

**Comment by melody7426** [comment] 2015-12-30 08:55
>it’s not an error or the cause of issue. How does your chrome extension URL look like?

`chrome-extension://pkfeekgnjjimgjhkgbbkofkfbmamfpnk/src/inject/options.html`

This is my URL.

**Comment by sergeche** [comment] 2015-12-30 09:02
Can you open Sources panel in DevTools of your extension and check if browser stylesheet is updated with editor updates?

**Comment by DeoThemes** [comment] 2015-12-30 09:13
> Yes, it’s an old plugin. Did you installed it via Package Control? Try to remove it and install again

Great, it worked. I removed plugin and installed it again via Package Control.
But not I have the same with https://github.com/livestyle/issues/issues/81#issuecomment-167883475
Sometimes stylesheets can't be detected, after few page/editor refreshes it works.

Cheers.

**Comment by sergeche** [comment] 2015-12-30 09:14
> Sometimes stylesheets can't be detected, after few page/editor refreshes it works.

You don’t see stylesheets from page or you don’t see updates from editor?

**Comment by melody7426** [comment] 2015-12-30 09:38
I have just checked both updates on chrome and sublime text. I see the event send (console.log) in your background but the layout does not update. The CSS file does not update with my editor.

**Comment by sergeche** [comment] 2015-12-30 09:50
Ok, will try to reproduce it

**Comment by melody7426** [comment] 2015-12-30 10:14
You’re really working hard everyday.

**Comment by DeoThemes** [comment] 2015-12-30 10:15
> You don’t see stylesheets from page or you don’t see updates from editor?

Don't see any stylesheets in chrome extension.

**Comment by sergeche** [comment] 2015-12-30 10:21
> Don't see any stylesheets in chrome extension.

Since I update extension often right now, most common cause of this problem is updated extension. After update, it looses connection with opened pages and can’t retrieve stylesheets. It can be easily fixed by closing devtools and refreshing page

**Comment by melody7426** [comment] 2015-12-30 10:59
I can see the stylesheet files at the popup, can selected files map with sublime text. But chrome does not sync with extension files. It still working with my file at localhost.

**Comment by franciscolourenco** [comment] 2015-12-30 12:38
Working for me. No way around having to open DevTools?

**Comment by sergeche** [comment] 2015-12-30 12:59
No, Chrome restricts access of content scripts to extensions so the only way is to work via DevTools api

**Comment by franciscolourenco** [comment] 2015-12-30 13:53
Another option would be a bookmarklet which injects the script.

**Comment by sergeche** [comment] 2015-12-30 13:56
It’s better to create a separate issue with this suggestion

**Comment by melody7426** [comment] 2016-01-04 07:19
hi Sergey,
Can I do anything for working with LiveStyle so far?

I'm working with chrome extension. At direct files like options.html
After page loaded, javascript will inject CSS file to HTML.
I can see and selected file from LiveStyle Popup. 
When I changed something, I see your background page append console.log but the sublime text does not update.

Thanks.

**Comment by sergeche** [comment] 2016-01-04 09:50
@melody7426 can you post a full screenshot of Chrome browser with your options page and LiveStyle popup opened?

**Comment by melody7426** [comment] 2016-01-04 10:22
![screenshot 2016-01-04 17 21 22](https://cloud.githubusercontent.com/assets/10826253/12087700/afe53db8-b307-11e5-9ffd-009a8bef97b4.png)

I hope it helpful

**Comment by melody7426** [comment] 2016-01-04 10:33
I sent the picture to your mail: serge.che@gmail.com

**Closed as completed** 2016-01-13 21:43 UTC
